<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Test Case
|--------------------------------------------------------------------------
*/

// Uses default TestCase

/*
|--------------------------------------------------------------------------
| Functions
|--------------------------------------------------------------------------
*/

function getSamplePlaceData(): array
{
    return [
        'businessId' => '1124715036',
        'title' => 'Pushkin',
        'description' => 'Legendary restaurant of Russian cuisine in a historic mansion on Tverskoy Boulevard.',
        'type' => 'restaurant',
        'url' => 'https://yandex.ru/maps/org/pushkin/1124715036/',
        'searchQuery' => 'restaurant',
        'longitude' => 37.600312,
        'latitude' => 55.764353,
        'address' => 'Tverskoy Boulevard, 26A, Moscow, Russia, 125009',
        'country' => 'Russia',
        'region' => 'Moscow',
        'city' => 'Moscow',
        'street' => 'Tverskoy Boulevard',
        'house' => '26A',
        'postalCode' => '125009',
        'status' => 'open',
        'isOpenNow' => true,
        'isVerifiedOwner' => true,
        'workingHoursText' => 'Daily, 12:00-00:00',
        'schedule' => [
            ['day' => 'Monday', 'hours' => '12:00–00:00'],
            ['day' => 'Tuesday', 'hours' => '12:00–00:00'],
        ],
        'rating' => 4.6,
        'ratingsCount' => 3150,
        'reviewCount' => 2847,
        'reviewAspects' => [
            ['name' => 'food', 'count' => 1200, 'positive' => 1100, 'neutral' => 50, 'negative' => 50],
            ['name' => 'service', 'count' => 800, 'positive' => 700, 'neutral' => 60, 'negative' => 40],
        ],
        'categories' => ['Restaurant', 'Banquet hall'],
        'phones' => ['+74955992664', '+74959999870'],
        'website' => 'https://cafe-pushkin.ru',
        'email' => 'info@cafe-pushkin.ru',
        'socialLinks' => [
            ['type' => 'instagram', 'url' => 'https://instagram.com/cafe_pushkin'],
            ['type' => 'facebook', 'url' => 'https://facebook.com/cafepushkin'],
        ],
        'features' => ['wi_fi' => true, 'food_delivery' => true, 'parking' => true],
        'chainName' => 'Maison Dellos',
        'chainId' => 'chain_001',
        'logoUrl' => 'https://avatars.mds.yandex.net/logo/pushkin.png',
        'photoCount' => 245,
        'photoUrlTemplate' => 'https://avatars.mds.yandex.net/get-altay/%s',
        'videoCount' => 3,
        'videos' => [
            ['url' => 'https://youtube.com/watch?v=abc', 'thumbnail' => 'https://img.youtube.com/vi/abc/0.jpg'],
        ],
        'bookingLinks' => [
            ['type' => 'BOOKING', 'url' => 'https://booking.pushkin.ru'],
        ],
        'bookingPartner' => [
            'partner' => 'YandexEda',
            'url' => 'https://eda.yandex.ru/restaurant/pushkin',
            'logo' => 'https://eda.yandex.ru/logo.png',
            'originalId' => 'yandex_123',
            'bookingType' => 'TABLE',
        ],
        'bookingAvailability' => null,
        'nearbyMetro' => [
            ['name' => 'Pushkinskaya', 'distance' => '150 m'],
        ],
        'nearbyStops' => [
            ['name' => 'Tverskaya pl.', 'distance' => '200 m'],
        ],
        'badges' => ['Michelin', 'Popular'],
        'awards' => ['michelin' => ['stars' => 1]],
        'snippet' => ['text' => 'Famous Russian cuisine restaurant', 'feature' => 'Michelin'],
        'regionId' => 213,
        'geoId' => 213,
        'shortTitle' => 'Pushkin',
        'timezoneOffset' => 10800,
        'panorama' => ['id' => 'pan_123', 'longitude' => 37.600312, 'latitude' => 55.764353],
        'bounds' => ['sw' => [37.59, 55.76], 'ne' => [37.61, 55.77]],
        'entrances' => [
            ['longitude' => 37.600312, 'latitude' => 55.764353, 'azimuth' => 90.0],
        ],
        'popularityHistogram' => ['Monday' => [10, 20, 30, 40, 50]],
        'sources' => [
            ['name' => 'Yandex', 'url' => 'https://yandex.ru'],
        ],
        'featureGroups' => [
            ['name' => 'Amenities', 'features' => ['wi_fi', 'parking']],
        ],
        'menu' => [
            'source' => 'YandexEda',
            'sourceUrl' => 'https://eda.yandex.ru',
            'totalItems' => 116,
            'items' => [['title' => 'Borsch', 'price' => '750', 'currency' => 'RUB', 'category' => 'Soups']],
        ],
        'additionalAddress' => '2nd floor, entrance from the courtyard',
        'legalInfo' => ['name' => 'OOO Maison Dellos', 'taxId' => '7704123456'],
        'actionButtons' => [
            ['type' => 'RESERVE', 'title' => 'Book a table', 'url' => 'https://booking.pushkin.ru'],
        ],
        'promo' => [
            'name' => 'Business lunch',
            'description' => '30% off weekday lunches',
            'url' => 'https://cafe-pushkin.ru/promo',
            'photoUrl' => 'https://avatars.mds.yandex.net/promo.jpg',
        ],
        'neurosummary' => 'Guests praise the exquisite Russian cuisine, elegant interior and attentive service.',
        'relatedPlaces' => null,
        'visitsHistogram' => null,
        'trustFeatures' => null,
        'discoveryCollections' => null,
        'mobileVideos' => null,
        'mobilePosts' => null,
        'reviews' => [
            ['reviewId' => 'r1', 'rating' => 5, 'text' => 'Amazing food and atmosphere'],
        ],
        'photos' => [
            ['url' => 'https://avatars.mds.yandex.net/photos/pushkin-1.jpg', 'category' => 'interior'],
        ],
        'posts' => [
            ['title' => 'New menu', 'date' => '2026-01-15'],
        ],
    ];
}

function getSampleReviewData(): array
{
    return [
        'reviewId' => 'rev_abc123def456',
        'businessId' => '1124715036',
        'businessTitle' => 'Pushkin',
        'businessUrl' => 'https://yandex.ru/maps/org/pushkin/1124715036/',
        'businessAddress' => 'Tverskoy Boulevard, 26A',
        'businessCity' => 'Moscow',
        'businessRating' => 4.6,
        'businessRatingsCount' => 3150,
        'businessCategories' => ['Restaurant', 'Banquet hall'],
        'neurosummary' => 'The reviewer highly praised the food quality and atmosphere.',
        'reviewAspects' => [
            ['name' => 'food', 'count' => 1200, 'positive' => 1100, 'neutral' => 50, 'negative' => 50],
        ],
        'rating' => 5,
        'text' => 'Excellent restaurant with stunning interior. The borsch was outstanding and the service was impeccable.',
        'date' => '2026-01-20T18:30:00Z',
        'authorName' => 'Alexei Petrov',
        'authorId' => 'user_789012',
        'authorAvatarUrl' => 'https://avatars.mds.yandex.net/avatars/user789.jpg',
        'authorProfileUrl' => 'https://yandex.ru/maps/profile/user_789012',
        'authorLevel' => 'Expert',
        'isAnonymous' => false,
        'authorAchievements' => ['Top Reviewer', '100+ Reviews'],
        'authorProfessions' => ['Food Critic'],
        'likeCount' => 12,
        'dislikeCount' => 1,
        'commentCount' => 3,
        'businessComment' => 'Thank you for your kind words, Alexei! We are glad you enjoyed your visit.',
        'businessCommentDate' => '2026-01-21T10:00:00Z',
        'photos' => [
            'https://avatars.mds.yandex.net/reviews/photo1.jpg',
            'https://avatars.mds.yandex.net/reviews/photo2.jpg',
        ],
        'videos' => [
            'https://avatars.mds.yandex.net/reviews/video1.mp4',
        ],
        'textLanguage' => 'en',
        'textTranslations' => ['Отличный ресторан с потрясающим интерьером.'],
        'isPublicRating' => true,
        'bold' => false,
        'keyPhrases' => [
            ['phrase' => 'stunning interior', 'sentiment' => 'positive'],
            ['phrase' => 'outstanding borsch', 'sentiment' => 'positive'],
        ],
    ];
}

function getSampleProductData(): array
{
    return [
        'title' => 'ASUS VivoBook 15 X1504VA-BQ613',
        'modelId' => 1971655847,
        'marketSku' => '101946073291',
        'wareId' => 'msrGU123abc',
        'oskuId' => 103594374410,
        'articleNumber' => '103594374410',
        'businessId' => 987654,
        'feedId' => 637707,
        'modelName' => 'ASUS VivoBook 15',
        'brand' => 'ASUS',
        'description' => 'Laptop ASUS VivoBook 15 with Intel Core i5, 16GB RAM, 512GB SSD, 15.6" FHD display.',
        'productUrl' => 'https://market.yandex.ru/product--asus-vivobook-15/1971655847',
        'canonicalUrl' => 'https://market.yandex.ru/product--asus-vivobook-15/1971655847?sku=101946073291',
        'productSlug' => 'asus-vivobook-15',
        'oskuSlug' => 'asus-vivobook-15-x1504va',
        'price' => 54990.0,
        'currency' => 'RUB',
        'priceYaBank' => 49491.0,
        'priceWithoutVat' => 45825.0,
        'rating' => 4.7,
        'ratingCount' => 856,
        'reviewCount' => 234,
        'purchaseCount' => 5600,
        'ratingDistribution' => ['5' => 450, '4' => 250, '3' => 100, '2' => 36, '1' => 20],
        'shopId' => 123456,
        'vendorId' => 789012,
        'supplierId' => 456789,
        'sellerName' => 'TechStore',
        'sellerRating' => 4.8,
        'sellerRatingCount' => 12500,
        'sellerLogo' => 'https://avatars.mds.yandex.net/sellers/techstore.png',
        'sellerSlug' => 'techstore',
        'placementType' => '3P',
        'hid' => 91013,
        'navnodeId' => 34512430,
        'departmentId' => 54440,
        'categoryName' => 'Laptops',
        'breadcrumbs' => [
            ['name' => 'Electronics', 'url' => '/catalog/electronics'],
            ['name' => 'Laptops', 'url' => '/catalog/laptops'],
        ],
        'isAvailable' => true,
        'stockCount' => 42,
        'minOrderQuantity' => 1,
        'maxOrderQuantity' => 5,
        'isCrossBorder' => false,
        'isExpress' => true,
        'isOnDemand' => false,
        'isUltima' => false,
        'sponsored' => false,
        'supplierType' => 1,
        'vat' => 'VAT_20',
        'paymentType' => 'PREPAYMENT',
        'paymentMethods' => ['BY_CARD_ONLINE', 'IN_CASH'],
        'isBnpl' => true,
        'offerFlags' => ['isFby', 'isPartialCheckoutAvailable'],
        'isInstallments' => false,
        'isDigital' => false,
        'deliveryPartnerTypes' => ['YANDEX_MARKET'],
        'hasVariants' => false,
        'delivery' => [
            'deliveryType' => 'PICKUP',
            'deliveryDays' => 1,
            'deliveryDateFrom' => '2026-02-16',
            'deliveryDateTo' => '2026-02-16',
            'deliveryText' => 'Tomorrow, pickup point',
            'precise' => true,
        ],
        'deliveryAlternatives' => [
            ['deliveryType' => 'COURIER', 'deliveryDays' => 2],
        ],
        'images' => [
            'https://avatars.mds.yandex.net/products/asus-1.jpg',
            'https://avatars.mds.yandex.net/products/asus-2.jpg',
            'https://avatars.mds.yandex.net/products/asus-3.jpg',
        ],
        'ugcImages' => [
            'https://avatars.mds.yandex.net/ugc/asus-user-1.jpg',
        ],
        'videos' => [
            ['url' => 'https://yandex.video/asus-review', 'duration' => 300],
        ],
        'specifications' => [
            ['name' => 'Processor', 'value' => 'Intel Core i5-1335U'],
            ['name' => 'RAM', 'value' => '16 GB'],
            ['name' => 'Storage', 'value' => '512 GB SSD'],
        ],
        'promos' => [
            ['type' => 'discount-by-payment-type', 'description' => '1% off with YaBank card'],
        ],
        'featureBadges' => [
            ['badgeType' => 'SIMPLEDiscountTokenType', 'badgeTitle' => '1% discount'],
        ],
        'benefitBadge' => 'Great price from a trusted seller',
        'shopSku' => '904106.ASUS-X1504VA',
        'feedOfferId' => '637707.904106.ASUS-X1504VA',
        'warehouseId' => '172',
        'searchPosition' => 3,
        'scrapedAt' => '2026-02-15T14:22:00Z',
        'reviews' => [
            ['rating' => 5, 'text' => 'Great laptop for the price'],
        ],
    ];
}

function getSampleListingData(): array
{
    return [
        'offerId' => '6352161035621587728',
        'offerType' => 'SELL',
        'offerCategory' => 'APARTMENT',
        'url' => 'https://realty.yandex.ru/offer/6352161035621587728',
        'shareUrl' => 'https://realty.yandex.ru/offer/6352161035621587728',
        'description' => 'Beautiful 3-room apartment in the center of Sochi, 600m from the sea.',
        'price' => [
            'value' => 16000000,
            'currency' => 'RUR',
            'period' => 'WHOLE_LIFE',
            'trend' => 'DECREASED',
            'previous' => 16900000,
            'hasPriceHistory' => true,
            'valuePerPart' => 307692,
            'unitPerPart' => 'SQUARE_METER',
        ],
        'area' => ['value' => 52.0, 'unit' => 'SQUARE_METER'],
        'roomsTotal' => 3,
        'floorsOffered' => [4],
        'floorsTotal' => 5,
        'ceilingHeight' => 2.6,
        'flatType' => 'SECONDARY',
        'openPlan' => false,
        'kitchenSpace' => ['value' => 7.0, 'unit' => 'SQUARE_METER'],
        'livingSpace' => ['value' => 32.0, 'unit' => 'SQUARE_METER'],
        'roomSpace' => null,
        'location' => [
            'address' => 'Сочи, микрорайон Центральный, улица Войкова, 33',
            'subjectFederationName' => 'Краснодарский край',
            'localityName' => 'Сочи',
            'point' => ['latitude' => 43.584198, 'longitude' => 39.72484, 'precision' => 'EXACT'],
            'parks' => [['name' => 'Навагинская', 'timeOnFoot' => 179]],
            'ponds' => [['name' => 'Чёрное море', 'timeOnFoot' => 526]],
            'station' => ['name' => 'Сочи', 'distanceKm' => 0.864],
        ],
        'author' => [
            'category' => 'AGENCY',
            'organization' => 'Агентство недвижимости «СОВА»',
            'agentName' => 'АН «СОВА»',
            'phones' => ['+79673813037'],
            'whatsappPhones' => ['+79324886757'],
        ],
        'phones' => [
            'phones' => [['phoneNumber' => '+79123827604']],
            'contacts' => [['phones' => [['phoneNumber' => '+79123827604']]]],
        ],
        'creationDate' => '2024-08-06T07:38:29Z',
        'updateDate' => '2026-02-17T06:28:00Z',
        'apartment' => ['renovation' => 'EURO', 'improvements' => ['AIRCONDITION' => true]],
        'building' => [
            'builtYear' => 1966,
            'buildingType' => 'BRICK',
            'parkingType' => 'OPEN',
            'improvements' => ['LIFT' => false, 'GUARDED' => true],
        ],
        'house' => ['bathroomUnit' => 'MATCHED', 'balconyType' => 'LOGGIA'],
        'lot' => null,
        'fullImages' => [
            'https://avatars.mds.yandex.net/get-realty-offers/photo1/large',
            'https://avatars.mds.yandex.net/get-realty-offers/photo2/large',
        ],
        'totalImages' => 20,
        'history' => null,
        'predictions' => [
            'predictedPrice' => ['min' => '15806000', 'max' => '19318000', 'value' => '17562000'],
        ],
        'active' => true,
        'dealStatus' => 'SALE',
        'exclusive' => true,
        'premium' => true,
        'promoted' => true,
        'raised' => true,
        'newBuilding' => false,
        'notForAgents' => false,
        'suspicious' => false,
        'trust' => 'NORMAL',
        'tags' => ['берег', 'парк', 'современный', 'школа'],
        'views' => 26,
        'uid' => '651138659',
        'platform' => 'PLATFORM_FEED',
        'partnerId' => '1069139472',
        'partnerName' => 'ООО СОВА',
        'clusterId' => '6352161035621587728',
        'clusterHeader' => true,
        'clusterSize' => 1,
        'supplyMap' => ['GAS' => true],
        'transactionConditionsMap' => ['MORTGAGE' => true],
        'agentFee' => null,
        'minRentPeriod' => null,
        'rentConditionsMap' => null,
        'utilitiesIncluded' => null,
        'offerLinks' => [
            'streetSearchLink' => 'https://realty.yandex.ru/sochi/kupit/kvartira/st-ulica-vojkova-17624/',
        ],
        'allowedCommunicationChannels' => ['COM_CALLS'],
        'tuzInfo' => ['campaignId' => 'b23248b8-c6b2-4e42-bdb0-0955b0cff269', 'active' => true],
        'trustedOfferInfo' => ['isFullTrustedOwner' => false],
        'remoteReview' => ['onlineShow' => false],
        'enrichedFields' => ['BUILD_YEAR', 'BUILDING_SERIES_ID'],
        'hasPaidCalls' => true,
        'newFlatSale' => false,
        'primarySaleV2' => false,
        'yandexRent' => false,
        'yandexProdaja' => false,
        'cashbackYandexPlus' => false,
        'withExcerpt' => false,
        'salesDepartments' => null,
        'siteInfo' => null,
    ];
}
